# Generated by Django 6.0.7 on 2026-07-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('super_admin', 'Super_Admin'), ('user', 'User')], default='super_admin', max_length=20),
        ),
    ]
